import React from 'react'
import './Animewatchlist.css'
import preview_BT from '../assets/budget-tracker.mp4';
export default function BudgetTracker() {
  return (
    <div>
        <div className="project-container">
            <div className="anime-watchlist">
                <div className="title-anime-watchlist-container">
                    <h2 className='h2'>
                        <a href='https://night2002.github.io/budget-tracker/'><div className="a-anime">Budget Tracker</div></a></h2>
                </div>
                <div className="anime-watchlist-details">
                <div className="description">
                <p className='p'>Budget Tracker is a React.js + Vite.js web-app is made for a company head to see the expenses and income of the various departments they lead,The data is color coded for effectiveness, You can learn about the trends of the sales generated by using a line chart graph. 
                <h4>Features :</h4>
                <p>- Uses react-chart-2 package.</p>
                <p>- Uses a Line graph to show the trend of the sales.</p>
                <p>- uses 'react.Usestate()' for conditional rendering.</p>
                <p>- Uses more simple yet elegant css such as transform.</p>
                </p>
                </div>
                <div className="video-container">
                    <iframe className='iframe'
                        src={preview_BT}
                        title='Anime watchlist preview'
                        width="800"
                        height="450"
                        // height="500"
                        allow="accelerometer;autoplay;clipboard-write;encrypted-media;gyrocsope;picture-in-picture"
                        allowFullScreen>     
                    </iframe>
                </div>
                </div>
               
            </div>
        </div>
        </div>
  )
}

